"""initial_schema

Revision ID: b5c7f68c8eb6
Revises: 
Create Date: 2026-03-06 01:29:32.734720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c7f68c8eb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'advisor', 'admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'rejected', name='user_status'), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("email ILIKE '%%@cloud.neduet.edu.pk'", name='ck_users_email_university_domain'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('cv_submissions',
    sa.Column('cv_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'pending_advisor', 'approved', 'rejected', name='cv_status'), nullable=False),
    sa.Column('rejection_comment', sa.Text(), nullable=True),
    sa.Column('career_counseling', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cv_id')
    )
    op.create_index('idx_student_status', 'cv_submissions', ['student_id', 'status'], unique=False)
    op.create_index(op.f('ix_cv_submissions_status'), 'cv_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_cv_submissions_student_id'), 'cv_submissions', ['student_id'], unique=False)
    op.create_table('academics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_id', sa.UUID(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('university', sa.String(length=150), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('gpa', sa.String(length=20), nullable=True),
    sa.Column('majors', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv_submissions.cv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academics_gpa'), 'academics', ['gpa'], unique=False)
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv_submissions.cv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv_submissions.cv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extra_curricular',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_id', sa.UUID(), nullable=True),
    sa.Column('activity', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv_submissions.cv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fyp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv_submissions.cv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fyp_company'), 'fyp', ['company'], unique=False)
    op.create_table('industrial_visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_id', sa.UUID(), nullable=True),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv_submissions.cv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_id', sa.UUID(), nullable=True),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('field', sa.Text(), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv_submissions.cv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('father_name', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=250), nullable=True),
    sa.Column('batch', sa.String(length=4), nullable=True),
    sa.Column('cell', sa.String(length=11), nullable=True),
    sa.Column('roll_no', sa.String(length=8), nullable=True),
    sa.Column('cnic', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv_submissions.cv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_info_batch'), 'personal_info', ['batch'], unique=False)
    op.create_table('references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('occupation', sa.Text(), nullable=True),
    sa.Column('relation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv_submissions.cv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv_submissions.cv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_table('references')
    op.drop_index(op.f('ix_personal_info_batch'), table_name='personal_info')
    op.drop_table('personal_info')
    op.drop_table('internships')
    op.drop_table('industrial_visits')
    op.drop_index(op.f('ix_fyp_company'), table_name='fyp')
    op.drop_table('fyp')
    op.drop_table('extra_curricular')
    op.drop_table('certificates')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_academics_gpa'), table_name='academics')
    op.drop_table('academics')
    op.drop_index(op.f('ix_cv_submissions_student_id'), table_name='cv_submissions')
    op.drop_index(op.f('ix_cv_submissions_status'), table_name='cv_submissions')
    op.drop_index('idx_student_status', table_name='cv_submissions')
    op.drop_table('cv_submissions')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
