"""update cv model

Revision ID: bd57d5e576a5
Revises: b5c7f68c8eb6
Create Date: 2026-03-08 00:26:26.382227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd57d5e576a5'
down_revision: Union[str, Sequence[str], None] = 'b5c7f68c8eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_submissions', sa.Column('student_image_url', sa.String(length=500), nullable=True))
    op.add_column('cv_submissions', sa.Column('cv_drive_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_submissions', 'cv_drive_url')
    op.drop_column('cv_submissions', 'student_image_url')
    # ### end Alembic commands ###
