"""upgraded models added new fields

Revision ID: f43b6e0d52c6
Revises: bd57d5e576a5
Create Date: 2026-03-09 21:35:23.352225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f43b6e0d52c6'
down_revision: Union[str, Sequence[str], None] = 'bd57d5e576a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academics', sa.Column('to_date', sa.Date(), nullable=True))
    op.add_column('academics', sa.Column('from_date', sa.Date(), nullable=True))
    op.drop_column('academics', 'year')
    op.add_column('internships', sa.Column('duties', postgresql.ARRAY(sa.Text()), nullable=False))
    op.alter_column('internships', 'organization',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('internships', 'from_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('internships', 'from_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('internships', 'organization',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('internships', 'duties')
    op.add_column('academics', sa.Column('year', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('academics', 'from_date')
    op.drop_column('academics', 'to_date')
    # ### end Alembic commands ###
