"""update user model and status

Revision ID: 5c8c438149f5
Revises: 88b531394060
Create Date: 2026-03-04 23:03:37.903083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8c438149f5'
down_revision: Union[str, Sequence[str], None] = '88b531394060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_status_enum = sa.Enum(
        'active',
        'inactive',
        'rejected',
        name='user_status'
    )
    user_status_enum.create(op.get_bind())
    op.add_column('users', sa.Column('clerk_user_id', sa.String(length=255), nullable=False))
    # 2️⃣ Then add column
    op.add_column(
        'users',
        sa.Column(
            'status',
            user_status_enum,
            nullable=False,
            server_default='active'  # IMPORTANT if table already has data
        )
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_column('users', 'status')
    op.drop_column('users', 'clerk_user_id')
    # ### end Alembic commands ###
